version: '3.4'

services:
  maincra:
    image: maincra
    build:
      context: Frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
  modsdownloader:
    image: modsdownloader
    build:
      context: Backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MODSPATH : /usr/src/app/modspath/
      ZIPPATH : /usr/src/app/zippath/
      ZIPNAMEWITHEXT : modsitos.zip
      PORT : 8000
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./zipFiles/
        target: /usr/src/app/zippath/
      - type: bind
        source: ./upload_data/
        target: /usr/src/app/modspath/