version: '3.4'

services:
  maincra:
    image: maincra
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 2G
    build:
      context: Frontend
      dockerfile: ./Dockerfile
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - 3000:80
  modsdownloader:
    image: modsdownloader
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 2G
    build:
      context: Backend
      dockerfile: ./Dockerfile
    restart: always
    environment:
      NODE_ENV: production
      MODSPATH : /usr/src/app/modspath/
      ZIPPATH : /usr/src/app/zippath/
      CLIENTMODSPATH: /usr/src/app/clientpath/
      WORLDPATH: /usr/src/app/world/
      BACKUPPATH: /usr/src/app/backups/
      ZIPNAMEWITHEXT : modsitos.zip
      #MONGOURL: 
      #SALT:
      #ACCESS_TOKEN_PRIVATE_KEY:
      #REFRESH_TOKEN_PRIVATE_KEY:
      PORT : 8000
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: /home/casmis123/zipfiles/
        target: /usr/src/app/zippath/
      - type: bind
        source: /home/casmis123/Minecraft/mods/
        target: /usr/src/app/modspath/
      - type: bind
        source: /home/casmis123/Minecraft/world/
        target: /usr/src/app/world/
      - type: bind
        source: /home/casmis123/clientfiles/
        target: /usr/src/app/clientpath/
      - type: bind
        source: /home/casmis123/backups/
        target: /usr/src/app/backups/