name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build ExpressApi and publish to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: Backend
          push: true
          tags: daves2126/arequipetapi:latest, daves2126/arequipetapi:${{ github.run_number }}
      - name: Build ReactJs and publish to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: Backend
          push: true
          tags: daves2126/arequipetweb:latest, daves2126/arequipetweb:${{ github.run_number }}